// Robust multi-year calibration of MLB Statcast Sprint Speed -> standardized 90 ft T90.
//
// Inputs (generated by fetch_statcast_running.mjs):
//   data/raw/statcast_running/running_splits_YYYY.csv
//   data/raw/statcast_running/sprint_speed_YYYY.csv
// Output:
//   outputs/derived/t90_bridge_calibration.json
//
// The current Baseball Savant Running Splits CSV uses fields such as
// `seconds_since_hit_010`, `seconds_since_hit_030`, `seconds_since_hit_090`.
// This script treats those explicit fields as the canonical source instead of guessing old header names.
//
// Validation goal:
// - pooled descriptive fit;
// - leave-one-year-out (LOYO) out-of-season prediction for 2017-2025;
// - compare Sprint Speed only vs Sprint+T10 vs Sprint+T30;
// - quantify how much acceleration/split information reduces T90 error.
//
// This validates MLB model structure. It does NOT license transferring coefficients to NPB+.

import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const IN = path.join(ROOT, 'data', 'raw', 'statcast_running');
const OUT = path.join(ROOT, 'outputs', 'derived', 't90_bridge_calibration.json');

function parseCsv(text) {
  const rows = [];
  let row = [], field = '', quoted = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (ch === '"') quoted = false;
      else field += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ',') { row.push(field); field = ''; }
    else if (ch === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (ch !== '\r') field += ch;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  if (!rows.length) return { headers: [], rows: [] };
  const headers = rows[0].map(x => x.trim());
  return {
    headers,
    rows: rows.slice(1)
      .filter(r => r.some(x => String(x ?? '').trim() !== ''))
      .map(r => Object.fromEntries(headers.map((h, i) => [h, r[i] ?? '']))),
  };
}

const num = v => {
  const n = Number(String(v ?? '').replace(/[%,\s]/g, ''));
  return Number.isFinite(n) ? n : null;
};
const mean = a => a.length ? a.reduce((s, x) => s + x, 0) / a.length : null;
const median = a0 => {
  const a = a0.filter(Number.isFinite).sort((a,b) => a-b);
  if (!a.length) return null;
  const m = Math.floor(a.length / 2);
  return a.length % 2 ? a[m] : (a[m-1] + a[m]) / 2;
};
const sdSample = a0 => {
  const a = a0.filter(Number.isFinite);
  if (a.length < 2) return null;
  const m = mean(a);
  return Math.sqrt(a.reduce((s,x) => s + (x-m)**2, 0) / (a.length-1));
};

function corrPairs(pairs) {
  const a = pairs.filter(([x,y]) => Number.isFinite(x) && Number.isFinite(y));
  if (a.length < 3) return null;
  const mx = mean(a.map(x => x[0])), my = mean(a.map(x => x[1]));
  let sxy=0,sxx=0,syy=0;
  for (const [x,y] of a) {
    sxy += (x-mx)*(y-my); sxx += (x-mx)**2; syy += (y-my)**2;
  }
  return sxx > 0 && syy > 0 ? sxy / Math.sqrt(sxx*syy) : null;
}

function solveLinear(A, b) {
  const n = b.length;
  A = A.map(r => [...r]); b = [...b];
  for (let i=0;i<n;i++) {
    let p=i;
    for (let j=i+1;j<n;j++) if (Math.abs(A[j][i]) > Math.abs(A[p][i])) p=j;
    [A[i],A[p]]=[A[p],A[i]]; [b[i],b[p]]=[b[p],b[i]];
    const d=A[i][i];
    if (!Number.isFinite(d) || Math.abs(d)<1e-12) return null;
    for (let k=i;k<n;k++) A[i][k]/=d;
    b[i]/=d;
    for (let j=0;j<n;j++) if (j!==i) {
      const f=A[j][i];
      for (let k=i;k<n;k++) A[j][k]-=f*A[i][k];
      b[j]-=f*b[i];
    }
  }
  return b;
}

function fitLinear(rows, features) {
  const a = rows.filter(r => Number.isFinite(r.t90) && features.every(k => Number.isFinite(r[k])));
  const p = features.length + 1;
  if (a.length <= p) return null;
  const M = Array.from({length:p},()=>Array(p).fill(0));
  const v = Array(p).fill(0);
  for (const r of a) {
    const x=[1,...features.map(k=>r[k])];
    for (let i=0;i<p;i++) {
      v[i]+=x[i]*r.t90;
      for (let j=0;j<p;j++) M[i][j]+=x[i]*x[j];
    }
  }
  const beta=solveLinear(M,v);
  if (!beta) return null;
  return {
    n:a.length,
    features,
    intercept:beta[0],
    coefficients:Object.fromEntries(features.map((k,i)=>[k,beta[i+1]])),
  };
}

function predict(model, row) {
  if (!model) return null;
  let y=model.intercept;
  for (const [k,c] of Object.entries(model.coefficients)) {
    if (!Number.isFinite(row[k])) return null;
    y += c*row[k];
  }
  return Number.isFinite(y) ? y : null;
}

function evalModel(rows, model) {
  const a=[];
  for (const r of rows) {
    const p=predict(model,r);
    if (Number.isFinite(p) && Number.isFinite(r.t90)) a.push({r,p,e:p-r.t90});
  }
  if (!a.length) return {n:0,mae:null,rmse:null,bias:null,r:null};
  return {
    n:a.length,
    mae:mean(a.map(x=>Math.abs(x.e))),
    rmse:Math.sqrt(mean(a.map(x=>x.e*x.e))),
    bias:mean(a.map(x=>x.e)),
    r:corrPairs(a.map(x=>[x.p,x.r.t90])),
  };
}

function collapseMean(rows, keys) {
  const out={};
  for (const k of keys) {
    const a=rows.map(r=>r[k]).filter(Number.isFinite);
    out[k]=a.length ? mean(a) : null;
  }
  return out;
}

const files=await readdir(IN);
const years=[...new Set(files.map(f=>Number(f.match(/_(20\d\d)\.csv$/)?.[1])).filter(Number.isFinite))].sort();
if (!years.length) throw new Error(`No Statcast running CSVs in ${path.relative(ROOT,IN)}`);

const all=[];
const diagnostics=[];
for (const year of years) {
  const splitPath=path.join(IN,`running_splits_${year}.csv`);
  const sprintPath=path.join(IN,`sprint_speed_${year}.csv`);
  let splitText,sprintText;
  try { splitText=await readFile(splitPath,'utf8'); sprintText=await readFile(sprintPath,'utf8'); }
  catch { continue; }
  const S=parseCsv(splitText), P=parseCsv(sprintText);
  const requiredSplit=['player_id','seconds_since_hit_010','seconds_since_hit_030','seconds_since_hit_090'];
  const requiredSprint=['player_id','sprint_speed'];
  const missingSplit=requiredSplit.filter(h=>!S.headers.includes(h));
  const missingSprint=requiredSprint.filter(h=>!P.headers.includes(h));
  if (missingSplit.length || missingSprint.length) {
    diagnostics.push({year,error:'required_header_missing',missingSplit,missingSprint,split_headers:S.headers,sprint_headers:P.headers});
    continue;
  }

  const byId=new Map();
  for (const r of S.rows) {
    const id=String(r.player_id??'').trim();
    const t90=num(r.seconds_since_hit_090);
    if (!id || !(t90>0)) continue;
    const rec={
      t10:num(r.seconds_since_hit_010),
      t30:num(r.seconds_since_hit_030),
      t60:S.headers.includes('seconds_since_hit_060') ? num(r.seconds_since_hit_060) : null,
      t90,
    };
    if (!byId.has(id)) byId.set(id,[]);
    byId.get(id).push(rec);
  }
  const split=new Map();
  for (const [id,a] of byId) split.set(id,{id,...collapseMean(a,['t10','t30','t60','t90']),split_rows:a.length});

  const sprint=new Map();
  for (const r of P.rows) {
    const id=String(r.player_id??'').trim();
    const v=num(r.sprint_speed);
    if (id && Number.isFinite(v)) sprint.set(id,{sprint:v});
  }

  let matched=0;
  for (const [id,a] of split) {
    const b=sprint.get(id);
    if (!b) continue;
    all.push({year,player_id:id,sprint:b.sprint,t10:a.t10,t30:a.t30,t60:a.t60,t90:a.t90,split_rows:a.split_rows});
    matched++;
  }
  diagnostics.push({year,split_players:split.size,sprint_players:sprint.size,matched});
}

if (all.length < 100) {
  await mkdir(path.dirname(OUT),{recursive:true});
  await writeFile(OUT,JSON.stringify({status:'FAILED_INSUFFICIENT_MATCHES',years,n:all.length,diagnostics},null,2));
  throw new Error(`Only ${all.length} matched player-seasons; inspect ${path.relative(ROOT,OUT)}`);
}

const definitions=[
  {key:'sprint_only',features:['sprint']},
  {key:'sprint_t10',features:['sprint','t10']},
  {key:'sprint_t30',features:['sprint','t30']},
];
const models={};
for (const d of definitions) {
  const model=fitLinear(all,d.features);
  models[d.key]={model,pooled_eval:evalModel(all,model)};
}

const loyo={};
for (const d of definitions) loyo[d.key]={folds:[],errors:[]};
for (const heldYear of years) {
  const train=all.filter(r=>r.year!==heldYear);
  const test=all.filter(r=>r.year===heldYear);
  for (const d of definitions) {
    const model=fitLinear(train,d.features);
    const e=evalModel(test,model);
    loyo[d.key].folds.push({held_year:heldYear,train_n:train.length,test_n:test.length,...e,model});
    for (const r of test) {
      const p=predict(model,r);
      if (Number.isFinite(p) && Number.isFinite(r.t90)) loyo[d.key].errors.push({year:heldYear,player_id:r.player_id,error:p-r.t90});
    }
  }
}
for (const d of definitions) {
  const x=loyo[d.key];
  const es=x.errors.map(r=>r.error);
  x.summary={
    n:es.length,
    mae:mean(es.map(Math.abs)),
    rmse:Math.sqrt(mean(es.map(e=>e*e))),
    bias:mean(es),
    fold_mae_median:median(x.folds.map(f=>f.mae).filter(Number.isFinite)),
    fold_mae_max:Math.max(...x.folds.map(f=>f.mae).filter(Number.isFinite)),
  };
  delete x.errors;
}

const sprintResidualModel=models.sprint_only.model;
const residualRows=all.map(r=>({
  ...r,
  sprint_only_residual:Number.isFinite(predict(sprintResidualModel,r)) ? r.t90-predict(sprintResidualModel,r) : null,
}));
const residual_correlations={
  t10:corrPairs(residualRows.map(r=>[r.t10,r.sprint_only_residual])),
  t30:corrPairs(residualRows.map(r=>[r.t30,r.sprint_only_residual])),
};

const adjacent={t90:[],sprint:[]};
const byPlayer=new Map();
for (const r of all) {
  if (!byPlayer.has(r.player_id)) byPlayer.set(r.player_id,[]);
  byPlayer.get(r.player_id).push(r);
}
for (const a0 of byPlayer.values()) {
  const a=[...a0].sort((x,y)=>x.year-y.year);
  for (let i=0;i<a.length-1;i++) if (a[i+1].year===a[i].year+1) {
    adjacent.t90.push([a[i].t90,a[i+1].t90]);
    adjacent.sprint.push([a[i].sprint,a[i+1].sprint]);
  }
}

const base=loyo.sprint_only.summary.mae;
const improvement={};
for (const key of ['sprint_t10','sprint_t30']) {
  const v=loyo[key].summary.mae;
  improvement[key]={
    absolute_mae_reduction_sec:Number.isFinite(base)&&Number.isFinite(v)?base-v:null,
    relative_mae_reduction:Number.isFinite(base)&&base>0&&Number.isFinite(v)?(base-v)/base:null,
  };
}

const report={
  status:'FULL_MLB_MULTIYEAR_VALIDATION_COMPLETE',
  created_at:new Date().toISOString(),
  source:'Baseball Savant Running Splits + Sprint Speed CSV',
  seasons:years,
  sample:{
    player_seasons:all.length,
    unique_players:byPlayer.size,
    sprint_mean:mean(all.map(r=>r.sprint)),
    sprint_sd:sdSample(all.map(r=>r.sprint)),
    t90_mean:mean(all.map(r=>r.t90)),
    t90_sd:sdSample(all.map(r=>r.t90)),
  },
  diagnostics,
  models,
  leave_one_year_out:loyo,
  acceleration_value:{
    residual_correlations,
    improvement_vs_sprint_only:improvement,
  },
  adjacent_year_repeatability:{
    n:adjacent.t90.length,
    t90_r:corrPairs(adjacent.t90),
    sprint_r:corrPairs(adjacent.sprint),
  },
  interpretation_guardrails:[
    'MLB Sprint Speed coefficients are calibrated only for MLB Statcast definitions represented in these CSVs.',
    'NPB+ officially calls its metric Sprint Speed, but public formula/window/aggregation equivalence to MLB Statcast is not established.',
    'Therefore the MLB coefficients must not be copied into the NPB+ model merely by unit conversion.',
    'The transferable conclusion is structural: acceleration/split information may materially improve 90ft prediction beyond Sprint Speed alone.',
  ],
};
await mkdir(path.dirname(OUT),{recursive:true});
await writeFile(OUT,JSON.stringify(report,null,2));
console.log(`T90 calibration v2: ${all.length} player-seasons, ${byPlayer.size} players, ${years[0]}-${years.at(-1)}`);
for (const d of definitions) console.log(`${d.key}: LOYO MAE=${loyo[d.key].summary.mae?.toFixed(4)}s RMSE=${loyo[d.key].summary.rmse?.toFixed(4)}s`);
console.log(`+T10 MAE reduction: ${(100*improvement.sprint_t10.relative_mae_reduction).toFixed(1)}%`);
console.log(`+T30 MAE reduction: ${(100*improvement.sprint_t30.relative_mae_reduction).toFixed(1)}%`);
console.log(`wrote ${path.relative(ROOT,OUT)}`);
