import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const P={queue:'outputs/derived/sp077_construct_complete_owner_review_queue_20260817.json',old:'outputs/derived/sp077_final_owner_review_queue_20260816.json',h2f:'outputs/derived/sp007_h2f_low_confidence_lane.json',physical:'data/manual/npb_speed_physical_evidence_full_20260809.json',recovered:'outputs/derived/sp017_physical_measurement_range_reclassification.json',anchors:'data/normalized/speed_historical_physical_measurements_2015_2026.json',stale:'outputs/derived/sp042_powerpro_stale_detector.json',x:'outputs/derived/speed_x_current_powerpro_clean_20260816.jsonl',lock:'docs/state/speed_owner_review_integrity_lock_20260817.json',ledger:'outputs/derived/sp078_owner_verdict_ledger_20260816.json',qa:'outputs/derived/qa_sp077_construct_complete_owner_review_queue_v2_20260817.json',audit:'docs/audits/sp077_construct_complete_owner_review_independent_qa_v2_20260817.md'};
const full=p=>path.join(ROOT,p), read=p=>fs.readFileSync(full(p),'utf8'), json=p=>JSON.parse(read(p));
const norm=v=>String(v??'').normalize('NFKC').replace(/[\s\u3000]/g,''), arr=v=>Array.isArray(v)?v:[];
const num=v=>(v===null||v===undefined||v==='')?null:(Number.isFinite(Number(v))?Number(v):null);
const errs=[],checks=[];const ck=(cond,label,detail='')=>{checks.push({label,pass:!!cond,detail});if(!cond)errs.push(`${label}${detail?`: ${detail}`:''}`);};
const has=(o,k)=>o!=null&&typeof o==='object'&&Object.prototype.hasOwnProperty.call(o,k);
const metricText=r=>`${r?.metric??''} ${r?.metric_raw??''} ${r?.metric_canonical??''} ${r?.start_protocol??''}`;
const isShort=r=>/(^|[^0-9])(10m|20m|30m|40m|50m|60yd|60-yard)([^0-9]|$)/i.test(metricText(r));
const srcSig=r=>JSON.stringify([num(r.measurement_year),r.metric??r.metric_canonical??r.metric_raw??null,num(r.value??r.seconds),r.source_url??null]);
const outSig=r=>JSON.stringify([num(r.measurement_year),r.metric??null,num(r.value??r.seconds),r.source_url??null]);
const multiset=a=>{const m=new Map();for(const x of a)m.set(x,(m.get(x)||0)+1);return m;};
const eqMulti=(a,b)=>{const m=multiset(a);for(const x of b)m.set(x,(m.get(x)||0)-1);return [...m.values()].every(v=>v===0);};
const q=json(P.queue),old=json(P.old),h2f=json(P.h2f),physical=json(P.physical),recovered=json(P.recovered),anchors=json(P.anchors),stale=json(P.stale),lock=json(P.lock),ledger=json(P.ledger);
const xRows=read(P.x).split(/\r?\n/).filter(Boolean).map(JSON.parse);
const qBy=new Map(arr(q.players).map(r=>[norm(r.identity?.player),r])), oldBy=new Map(arr(old.players).map(r=>[norm(r.identity?.player),r]));
ck(q.schema_version==='sp077_construct_complete_owner_review_queue_20260817','schema');ck(arr(q.players).length===100,'population',String(arr(q.players).length));ck(qBy.size===100,'unique normalized players',String(qBy.size));ck(new Set(arr(q.players).map(r=>r.queue_row_key)).size===100,'unique queue keys');
ck(lock.locked===true,'owner-review integrity lock remains true');ck(arr(ledger.records).length===0&&Number(ledger.owner_verdict_count)===0,'SP078 ledger remains empty');ck(/LOCK/i.test(String(q.status)),'candidate explicitly locked',String(q.status));
const required=['construct_contract','top_speed_evidence','acceleration_h2f_t90_evidence','short_distance_physical_evidence','historical_physical_temporal_context','sp021_high_confidence_anchor_context','statistical_proxy_context','game_context_proxy_breakdown','community_physical_context','technique_separation_contract','powerpro_review_context','source_scope_guard','missingness_and_provenance_contract'];
for(const r of q.players){for(const f of required)ck(has(r,f),`${r.identity.player} has ${f}`);const o=oldBy.get(norm(r.identity.player));ck(!!o,`${r.identity.player} old queue identity`);if(o){ck(num(r.top_speed_evidence?.npb_plus_top_speed_kmh)===num(o.current_physical_evidence?.npb_plus_top_speed_kmh),`${r.identity.player} top speed source exact`);ck(JSON.stringify(r.statistical_proxy_context)===JSON.stringify(o.statistical_proxy_context),`${r.identity.player} statistical context exact`);}ck(r.construct_contract?.top_speed_is_full_construct===false,`${r.identity.player} top speed not full construct`);ck(r.construct_contract?.stealing_and_baserunning_technique_are_separate===true,`${r.identity.player} construct technique separation`);ck(r.source_scope_guard?.npb_plus_hp_to_1b_sec==='MISATTRIBUTED_SOURCE_FAIL_CLOSED',`${r.identity.player} NPB+ hp_to_1b fail closed`);ck(r.source_scope_guard?.h2f_construct_lane_preserved===true,`${r.identity.player} independent H2F retained`);ck(r.technique_separation_contract?.stealing_and_baserunning_abilities_require_residual_or_separate_model===true,`${r.identity.player} technique residual/separate`);const g=r.game_context_proxy_breakdown;if(g?.evidence_state==='AVAILABLE_MIXED_PROXY'){ck(g.role==='MIXED_GAME_CONTEXT_PROXY_NOT_DIRECT_PHYSICAL_TEACHER',`${r.identity.player} game-context role`);ck(!has(g.raw,'SB')&&!has(g.raw,'CS')&&!has(g.z,'SB')&&!has(g.z,'CS'),`${r.identity.player} steals excluded from base-speed components`);}ck(r.historical_physical_temporal_context?.injury_context?.no_negative_inference===true,`${r.identity.player} injury missingness bounded`);ck(r.historical_physical_temporal_context?.age_context?.no_negative_inference===true,`${r.identity.player} age missingness bounded`);}
// SP-007 exact values, using source-derived expected player union rather than a hand-coded count.
const normal=arr(h2f.normal_swing?.players),bunt=arr(h2f.bunt?.players);const h2fExpected=new Set();for(const s of normal){const k=norm(s.canonical_name??s.player);if(!qBy.has(k))continue;h2fExpected.add(k);ck(num(qBy.get(k).acceleration_h2f_t90_evidence?.normal_swing_h2f?.seconds)===num(s.seconds),`H2F normal ${s.canonical_name??s.player}`);}for(const s of bunt){const k=norm(s.canonical_name??s.player);if(!qBy.has(k))continue;h2fExpected.add(k);ck(num(qBy.get(k).acceleration_h2f_t90_evidence?.bunt_h2f?.seconds)===num(s.seconds),`H2F bunt ${s.canonical_name??s.player}`);}
// Raw/reclassified short-distance and historical evidence exact multiset preservation.
const pBy=new Map(arr(physical.players).map(x=>[norm(x.player),x])), recBy=new Map();for(const x of arr(recovered.records)){const k=norm(x.canonical_name??x.raw_name??x.player);if(!recBy.has(k))recBy.set(k,[]);recBy.get(k).push(x);}for(const r of q.players){const k=norm(r.identity.player),raw=arr(pBy.get(k)?.records),rec=recBy.get(k)??[];const es=[...raw.filter(isShort),...rec.filter(isShort)].map(srcSig),as=arr(r.short_distance_physical_evidence?.records).map(outSig);ck(eqMulti(es,as),`${r.identity.player} short-distance multiset`,`expected=${es.length} actual=${as.length}`);const eh=[...raw,...rec].filter(x=>{const y=num(x.measurement_year);return y==null||y<2026;}).map(srcSig),ah=arr(r.historical_physical_temporal_context?.records).map(outSig);ck(eqMulti(eh,ah),`${r.identity.player} historical multiset`,`expected=${eh.length} actual=${ah.length}`);}
// SP-021 anchor groups: preserve all raw rows inside 113 deduplicated anchor groups; current100 overlap is derived from source.
const accepted=arr(anchors.records).filter(x=>x.bank_acceptance_status==='ACCEPTED_HIGH_CONFIDENCE'),groups=new Map();for(const x of accepted){const id=x.selected_anchor_id||x.same_measurement_cluster_id||x.raw_id;if(!groups.has(id))groups.set(id,[]);groups.get(id).push(x);}ck(accepted.length===140,'SP021 accepted raw baseline',''+accepted.length);ck(groups.size===113,'SP021 dedup anchor baseline',''+groups.size);for(const [id,rs] of groups){ck(new Set(rs.map(x=>norm(x.player))).size===1,`SP021 ${id} single-player group`);}let expA=0,actA=0,expP=0,actP=0;for(const r of q.players){const k=norm(r.identity.player);const eg=[...groups].filter(([,rs])=>norm(rs[0].player)===k);const ag=arr(r.sp021_high_confidence_anchor_context?.anchors);expA+=eg.length;actA+=ag.length;if(eg.length)expP++;if(ag.length)actP++;ck(ag.length===eg.length,`${r.identity.player} SP021 group count`,`expected=${eg.length} actual=${ag.length}`);for(const [id,rs] of eg){const a=ag.find(z=>z.anchor_id===id);ck(!!a,`${r.identity.player} SP021 ${id} present`);if(a){ck(a.raw_record_count===rs.length,`${r.identity.player} SP021 ${id} raw count`);const expectedRows=rs.map(x=>JSON.stringify([x.raw_id,num(x.measurement_year),x.metric,num(x.value),x.source_url??null]));const actualRows=arr(a.records).map(x=>JSON.stringify([x.raw_id,num(x.measurement_year),x.metric,num(x.value),x.source_url??null]));ck(eqMulti(expectedRows,actualRows),`${r.identity.player} SP021 ${id} raw preservation`);}}}ck(expA===actA,'SP021 current100 anchor total',`expected=${expA} actual=${actA}`);ck(expP===actP,'SP021 current100 player total',`expected=${expP} actual=${actP}`);
// PowerPro review context exact against SP-042.
const staleRows=arr(stale.rows??stale.players),staleBy=new Map(staleRows.map(x=>[norm(x.player),x]));let staleN=0;for(const r of q.players){const s=staleBy.get(norm(r.identity.player)),avail=r.powerpro_review_context?.evidence_state==='AVAILABLE_REVIEW_CONTEXT';if(avail)staleN++;ck(avail===!!s,`${r.identity.player} stale presence`);if(s&&avail)ck(JSON.stringify(r.powerpro_review_context.stale_detector)===JSON.stringify(s),`${r.identity.player} stale row exact`);}ck(staleN===staleBy.size,'PowerPro context source coverage',`queue=${staleN} source=${staleBy.size}`);
// Community availability exact against clean bounded X player set.
const xNames=new Set(xRows.map(x=>norm(x.player??x.canonical_player??x.subject_player??x.player_name)).filter(k=>qBy.has(k)&&k));let commN=0;for(const r of q.players){const avail=r.community_physical_context?.evidence_state==='AVAILABLE_BOUNDED';if(avail)commN++;ck(avail===xNames.has(norm(r.identity.player)),`${r.identity.player} community presence`);}ck(commN===xNames.size,'community source coverage',`queue=${commN} source=${xNames.size}`);
const coverage={players:q.players.length,h2f_source_current100_players:h2fExpected.size,acceleration_available:q.players.filter(r=>r.acceleration_h2f_t90_evidence?.evidence_state==='AVAILABLE_BOUNDED').length,short_distance_available:q.players.filter(r=>r.short_distance_physical_evidence?.evidence_state==='AVAILABLE_BOUNDED').length,historical_available:q.players.filter(r=>r.historical_physical_temporal_context?.evidence_state==='AVAILABLE_BOUNDED').length,sp021_expected_current100_anchors:expA,sp021_actual_current100_anchors:actA,sp021_current100_players:actP,game_proxy_available:q.players.filter(r=>r.game_context_proxy_breakdown?.evidence_state==='AVAILABLE_MIXED_PROXY').length,powerpro_context:staleN,community_context:commN};
const result={schema_version:'qa_sp077_construct_complete_owner_review_queue_v2_20260817',generated_at:'2026-08-17',status:errs.length?'FAIL':'PASS',checks_total:checks.length,checks_passed:checks.filter(x=>x.pass).length,checks_failed:errs.length,coverage,errors:errs,checks};fs.writeFileSync(full(P.qa),JSON.stringify(result,null,2)+'\n');const md=['# SP-077 construct-complete owner-review independent QA v2','',`Status: **${result.status}**`,`Checks: ${result.checks_passed}/${result.checks_total} PASS; ${result.checks_failed} FAIL`,'','## Coverage','',...Object.entries(coverage).map(([k,v])=>`- ${k}: ${v}`),'','## Guards','','- Source-derived expectations are used for H2F/community/PowerPro coverage; no hand-tuned player count is used to make the queue pass.','- SP-021 raw rows are grouped, not discarded, under deduplicated anchor IDs.','- Integrity lock remains active and SP-078 remains empty.','- Top speed is one construct lane only.','',...(errs.length?['## Errors','',...errs.slice(0,200).map(e=>`- ${e}`),'']:[])].join('\n');fs.mkdirSync(path.dirname(full(P.audit)),{recursive:true});fs.writeFileSync(full(P.audit),md+'\n');console.log(JSON.stringify({status:result.status,checks_passed:result.checks_passed,checks_failed:result.checks_failed,coverage,first_errors:errs.slice(0,20)}));if(errs.length)process.exit(1);
