// Production-facing SP-100 wire.  This exposes a current-2026 physical layer
// only; it deliberately does not create an SP-079 practical reappraisal.
import { buildNpbTopSpeedPrimary } from './sp100_npb_primary_speed.mjs';
import { speedRating } from './running.mjs';

const round1 = value => Number.isFinite(value) ? Math.round(value * 10) / 10 : null;
const clampDisplay = value => value == null ? null : Math.max(1, Math.min(100, value));

function provisionalDisplayPoint(z, cfg) {
  const preScale = speedRating(z, cfg);
  const scale = cfg?.scale_calibration?.applied?.走力;
  const mapped = scale ? scale.intercept + scale.slope * preScale : preScale;
  return {
    pre_scale_rating: round1(preScale),
    provisional_display_point: round1(clampDisplay(mapped)),
    display_scale_status: 'PROVISIONAL_PENDING_SP-071_ENGINE_BRIDGE',
  };
}

/**
 * Resolve one current physical speed record under the explicit owner-approved
 * N-primary architecture. `statisticalContext` is retained verbatim as a
 * labelled S context/fallback record and is never used in this calculation.
 */
export function resolveSp100ProductionPhysicalSpeed({
  root,
  physicalEvidenceSeason,
  playerName,
  stablePlayerKey = null,
  cfg,
  statisticalContext = null,
}) {
  const n = buildNpbTopSpeedPrimary({ root, physicalEvidenceSeason, playerName, stablePlayerKey });
  const s = statisticalContext == null ? null : {
    ...statisticalContext,
    role: 'S_CONTEXT_OR_FALLBACK_ONLY_NOT_ARITHMETIC_BLEND',
  };
  if (!n) {
    return {
      architecture: 'N_PRIMARY_S_CONTEXT_OR_FALLBACK',
      selection: s ? 'S_FALLBACK_NO_CURRENT_YEAR_N' : 'NO_CURRENT_YEAR_N_OR_S',
      physical_evidence_season: Number(physicalEvidenceSeason) || null,
      n_primary: null,
      statistical_context: s,
      no_arithmetic_n_s_blend: true,
      scope: 'No final practical rating is generated by this layer.',
    };
  }
  const display = provisionalDisplayPoint(n.npb_top_speed_z, cfg);
  return {
    architecture: n.architecture,
    selection: 'N_PRIMARY_CURRENT_2026',
    physical_evidence_season: n.appraisal_year,
    n_primary: {
      stable_player_key: n.stable_player_key,
      production_player_id: n.production_player_id,
      top_speed_kmh: n.top_speed_kmh,
      npb_top_speed_z: n.npb_top_speed_z,
      current_cohort: n.current_cohort,
      measurement_reliability: n.measurement_reliability,
      exposure_context: n.exposure_context,
      source_season_label: n.source_season_label,
      provenance: n.provenance,
      ...display,
    },
    statistical_context: s,
    no_arithmetic_n_s_blend: true,
    fallback_policy: n.fallback_policy,
    scope: 'Current 2026 physical/rank layer only; no final practical rating is generated by this layer.',
  };
}
